### ISSUE TITLE
Calibration Issue

### ISSUE THREAD

**Issue by bpvarsity** [bigtreetech/BTT002-V1.0#4]
Installed on a stock MK3S and when I do Z Home or bed level the extruder and nozzle dive into my bed. What do I need to change?

**Comment by thisiskeithb** [comment]
In case someone else comes across this issue: Don’t forget to remove the diag pins on Z and E drivers or this will happen 🙂

**Comment by Afterschnitzel** [comment]
Thanks, you saved mi life :-D
